---
title: "p8105_hw2_rd3227"
author: "Ruihan Ding"
date: "2025-09-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# Problem 1

Clean the data in pols-month.csv

```{r}
# import dataset
pols_df = 
  read_csv(
    "fivethirtyeight/pols-month.csv", 
    na = c("NA", ".", ""), 
    show_col_types = FALSE
    ) |> 
  janitor::clean_names() |> 
  
# break up the variable mon into integer variables year, month, and day
  separate(
    mon, into = c("year", "month", "day"), sep = "-",
  ) |> 
  mutate(across(c(year:day), as.integer)) |> 

# replace month number with month name
  mutate(month = factor(month.name[month], levels = month.name)) |> 

# create a president variable
  mutate(
    president = case_when(
      prez_gop == 1 ~ "dem",
      prez_dem == 1 ~ "gop"
    )) |> 

# remove unnecessary columns
  select(-prez_gop, -prez_dem, -day)

```

Clean the data in snp.csv

```{r}
# import dataset
snp_df = 
  read_csv(
    "fivethirtyeight/snp.csv", 
    na = c("NA", ".", ""),
    show_col_types = FALSE
    ) |> 
  janitor::clean_names() |> 

# match the year and month format to the previous dataframe
  separate(
    date, into = c("month", "day", "year"), sep = "/",
  ) |> 
  mutate(across(c(month:year), as.integer)) |> 
  mutate(month = factor(month.name[month], levels = month.name)) |> 
  mutate(
    year = if_else(year < 20, 2000 + year, 1900 + year)) |> 

# arrange and organize
  select(year, month, everything(), -day) |> 
  arrange(year, month)

```

Clean the data in unemployment.csv

```{r}
# import dataset
unepm_df = 
  read_csv(
    "fivethirtyeight/unemployment.csv", 
    na = c("NA", ".", ""),
    show_col_types = FALSE
    ) |> 
  janitor::clean_names() |> 

# make month a factor variable
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    month = factor(
    str_to_title(month), 
    levels = month.abb,
    labels = month.name
      )) |> 

# arrange according to time
  arrange(year, month)

```










